### PR TITLE
Use upack2

### LINKED ISSUE #2: Update to use upack 2.x
Right now we use an ancient version of upack.exe - change to use the latest version of upack and make sure that it's included in the package itself

### PR DESCRIPTION
**Pull request by skovsende**
Fixes #2 and #14

### CODE REVIEW

**Comment by skovsende** [comment]
Yes, upack is MIT licensed. The real solution is to use their .net library instead though, but that will come another day :)

**Comment by skovsende** [comment]
But well spotted - things I need to get used to checking for when I'm doing public stuff. Life behind the corporate firewall is much simpler! ;)

**Comment by gep13** [comment]
@skovsende okay, just wanted to check.  In order to be 100% compliant, it will likely be necessary to include a copy of the license for the exe in the NuGet package, or at least mention it "somewhere" that it is being used under that license?

**Comment by skovsende** [comment]
You are absolutely right - #17 created to fix that

**Pull request merged**
